### ISSUE TITLE
Build using autotools

### ISSUE THREAD

**Issue by tahini** [chairemobilite/trRouting#12]
Autotools provide a known and common way to build applications from source and can take care of ensuring all dependencies are available, suggesting which packages to install. One can configure the build this way. So the usual build process would be

[./bootstrap] (may not be necessary here)
./configure [--enableAlgorithmX] with CSA being the default one
make
sudo make install

**Comment by greenscientist** [comment]
I've done that so many times, I'll look into it

**Comment by tahini** [comment]
> I've done that so many times, I'll look into it

Excellent, thanks!

Do you have any opinion/facts whether to use autotools or cmake toolchain? I briefly discussed with people who did HPC (which you might know too), and they told me that it really depends, some apps do better with llvm, others with gcc. I had postponed a more complete conversation for when backyard bbq are allowed.

**Comment by greenscientist** [comment]
The llvm vs gcc is orthogonal to the build tools. You can use either with autotools or cmake. 

As for cmake vs autotools, I had a brief tought it. (Specially since OSRM uses cmake). 
I ended up decided to continue with autotools because: 
1- I'm more familiar with it and I find cmake always a bit clumsy to use. 
2- The trRouting project is simple and all in C++, which is well supported 
3- Autotools is better known (I think) and supported in the open source world
4- Given the size, we can always decide to switch, specially if we decided to converge to some other solution for other parts of the project

**Comment by greenscientist** [comment]
J'ai un prototype qui fonctionne avec clang++, j'ai encore quelques problèmes de linking avec G++. Il me reste aussi à faire la détection automatique d'OSRM (et des autres dépendances)

**Comment by kaligrafy** [comment]
everything compiles correctly on macos Catalina
