### ISSUE TITLE
The max_egress_travel_time_seconds is never considered

### ISSUE THREAD

**Issue by tahini** [chairemobilite/trRouting#97]
It is possible to set a parameter called max_egress_travel_time_seconds when doing a query, but that parameter is never considered.

The osrm_fetcher compares access time (params.maxAccessWalkingTravelTimeSeconds), but params.maxEgressWalkingTravelTimeSeconds is never used in the code.

2 options:

1- Fix it and send to the osrm_fetch the maximal value to consider, access or egress time, depending on the context.

2- ~~Remove the max egress travel time parameter and consider symetry between access and egress.~~

@kaligrafy  which option is to be implemented? And long live unit tests! :p

**Comment by kaligrafy** [comment]
Since it is not too hard, I would implement it, but keep it optional (if max access walking travel time seconds is set, use it instead). When we will do multimodal routing, it will be quite useful, because the access and egress modes could be different (walking vs cycling or even car drving vs walking)
